### ISSUE TITLE
sncli constantly crashing, (offline, connection error) after editing notes

### ISSUE THREAD

**Issue by chkiss** [insanum/sncli#101]
I just started using sncli last week and I love it. That said, in just a few days I have lost notes, learned how to recover them from the /tmp/ directory, and learned how to set the /tmp/ directory not to delete on reboot due to more lost notes, etc. My biggest problem is that the client seems to go offline all the time and is often unresponsive (freezes after editing a note, sometimes never recovering and forcing a ctrl+c)

So far, I haven't been able to predictably reproduce much. Checking the logs after my status changed to "offline, connection error" only really showed "ERROR: Failed to get note list from server" as far as I can tell.

Here's a fuller sncli log of the last few minutes. Is there anything obviously going wrong here? I'm definitely not going offline as I'm on Zoom meetings all day. The "S" key doesn't bring the status back online.
[sncli-github.log](https://github.com/insanum/sncli/files/5219565/sncli-github.log)

**Comment by swalladge** [comment]
@chkiss sorry you're having this problem.  I can't think of why - perhaps the connection to the simplenote api is just very slow?  Nothing is async, so if it's always waiting for api requests to update notes, it could cause it to be unresponsive. 

> Is there anything obviously going wrong here? 

This looks pretty normal; just polling for notes updates; one failed.  Perhaps the application is getting rate limited maybe. hmmm.

Sorry I can't help much.  Let us know if you discover anything new or make any progress debugging. :)

**Comment by chkiss** [comment]
Thank you for checking out the log.

I'll try to keep working on reproducibility as it could just be something
with my workflow.

**Comment by chkiss** [comment]
I have noticed that sncli says it's online when I get back to it after my computer was asleep for an extended period, and if I go into a note it will let me edit it like normal. But if I hit j/k and refresh the display, it updates to "offline, connection error." Either way, note edits are at risk of being lost without a sync (but can be recovered from /tmp/).

I'm also thinking this is the same issue as #87.

**Comment by chkiss** [comment]
I still have this issue when I leave sncli open but put my laptop to sleep and wake it back up. To avoid data loss, I've now switched my workflow to just use sncli on an eternal terminal (basically ssh) session to a VPS. I'll close this ticket as I'm no longer affected by it and 87 is an older, still-open issue.

Thanks!
