### ISSUE TITLE
Opening note from command line is painfully slow

### ISSUE THREAD

**Issue by drewauff** [insanum/sncli#102]
sncli opens perfectly ok (a little slow if im honest but acceptable), however opening a note it is painfully slow at
around 5-7 seconds.

**Comment by swalladge** [comment]
Sorry to hear, that must be annoying.  Could you share the logs, and the command/process you're using to open a note (ie. exactly what are you doing, so that we can reproduce it)?

**Comment by drewauff** [comment]
the command Im using is : `sncli --key=THEKEYGOESINHERERECATEDFORPRIVACY edit'`

as for the logs, where is it?

**Comment by swalladge** [comment]
@drewauff thanks. :) 

So I don't see anything unusual in the logs, but I suspect it's the syncing process that happens by default before opening the note that slows things down. Could you try disabling sync in the edit command and let us know if that speeds it up?: `sncli --key=THEKEYGOESINHEREREDACTEDFORPRIVACY --nosync edit`

**Comment by drewauff** [comment]
yeah, that makes quite an improvement. brings it almost on par with main sncli. Thanks 👍🏽

**Comment by swalladge** [comment]
Great!  Just be aware that this means the note you're editing may not be the latest version, and I don't think it will sync after closing either.  You may want to automatically periodically run `sncli sync` (or something else; I don't know your workflow) to ensure that notes are always up to date.

**Comment by drewauff** [comment]
I was thinking to to setup a cron job for sync, would this do the trick?

**Comment by swalladge** [comment]
@drewauff yep that would work. :+1:
