### ISSUE TITLE
Login issues 

### ISSUE THREAD

**Issue by giuli007** [insanum/sncli#109]
Since last Sunday sncli is failing to login (tried with a couple of different accounts I have) showing this message
`Simplenote (offline: login failed; check username and password)`

An excerpt from the logs
```
2021-07-04 02:15:31,482 [DEBUG] sncli logging initialized
2021-07-04 02:15:31,674 [DEBUG] Starting new HTTPS connection (1): auth.simperium.com:443
2021-07-04 02:15:32,253 [DEBUG] https://auth.simperium.com:443 "POST /1/chalk-bump-f49/authorize/ HTTP/1.1" 400 15
2021-07-04 02:15:32,256 [DEBUG] Auth error: 400 Client Error: Bad Request for url: https://auth.simperium.com/1/chalk-bump-f49/authorize/
2021-07-04 02:15:33,364 [DEBUG] Sync worker: started
2021-07-04 02:15:33,365 [DEBUG] Starting full sync
2021-07-04 02:15:33,366 [DEBUG] ERROR: Failed to get note list from server
2021-07-04 02:15:33,366 [DEBUG] Full sync completed
```

Examining the response (`r.text`) from https://github.com/swalladge/simperium-python3/blob/master/simperium/core.py#L48 shows `missing api key`

That makes me think that maybe the token/api key being used by sncli (https://github.com/insanum/sncli/blob/master/simplenote_cli/simplenote.py#L32) has been revoked? Or that there is some other kind of problem with the simperium API?

**Comment by giuli007** [comment]
Found the issue and opened https://github.com/swalladge/simperium-python3/pull/1 on the library with a fix

**Comment by giuli007** [comment]
In the meantime, until the above fix gets merged and new versions of simperium-python3 and sncli get released, people could try the following to run sncli together with the proposed fix (as long as they are ok to run it from the repo).
Beware that this requires having `pipenv` installed somewhere (ideally in a virtualenv); and then let pipenv create a different virtualenv where to install sncli.
This is a bit hacky and while I dont think it should cause any issue (the fix simply uses a new header) do it at your own risk.

```
pip install pipenv # ideally do this from a virtualenv if you don want to install pipev system wide
git clone https://github.com/insanum/sncli
cd sncli
PIPENV_IGNORE_VIRTUALENVS=1 pipenv install -e git+https://github.com/giuli007/simperium-python3.git@auth_using_X_Simperium_API_Key_header#egg=Simperium3
PIPENV_IGNORE_VIRTUALENVS=1 pipenv install
```
Which should result in a new virtualenv where sncli is installed using the fixed version of the library.

You can use it by either
```
cd sncli
PIPENV_IGNORE_VIRTUALENVS=1 pipenv shell
sncli
```

or locate where pipenv installed its virualenv and run sncli directly from there (`sncli-LXiRhWUH` from below will be different for each installation
```
~/.local/share/virtualenvs/sncli-LXiRhWUH/bin/sncli
```

**Comment by swalladge** [comment]
Thanks @giuli007 !  I'll review https://github.com/swalladge/simperium-python3/pull/1 asap and get a new sncli release sorted. :+1:

**Comment by swalladge** [comment]
@giuli007 I tested logging in with sncli with the current release of simperium-python3, and your branch.  Both work equally well. :thinking: 

Could you and @noooxxi check if the issue has been resolved for you?  Perhaps it was a temporary issue on simplenote's side.

**Comment by giuli007** [comment]
Hi @swalladge I just tried again and I am still seeing the issue.

**Comment by noooxxi** [comment]
> Hi @swalladge I just tried again and I am still seeing the issue.

Yes, @swalladge, I updated my system and even reinstalled sncli. The problem remains. :cry:

**Comment by swalladge** [comment]
Thanks @giuli007 @noooxxi :)

**Comment by fredbsc** [comment]
Same issue here ... Thanks for any help!

**Comment by swalladge** [comment]
@fredbsc yep we're working on it.  Expect a new release within the next day or so with a fix. :D

**Comment by swalladge** [comment]
@fredbsc @noooxxi @giuli007 a new release for the [Simperium3](https://pypi.org/project/Simperium3/0.1.4/) dependency has been pushed, which includes @giuli007's fix.  If you installed via pip or from source, please reinstall or update your dependencies to get the latest version. :)

**Comment by noooxxi** [comment]
Thank you! Everything seems to be working again now ☺️
