### ISSUE TITLE
Support for Emacs as editor (SOLVED)

### ISSUE THREAD

**Issue by linuxsquad** [insanum/sncli#12]
First, thanks for the software. I have a great affinity to many CLI tools, and glad to see feature - rich implementaion.

One request, how much work needed to  replace VI with emacs?

Thanks

Oleg

**Comment by insanum** [comment]
It should just work after setting your EDITOR environment variable.

Let me know... :-)

- e

**Comment by linuxsquad** [comment]
I've set env EDITOR=emacs, but sncli was not picking this up and continuing  to use VI.

Well... then I just went and added config like this

>cfg_editor = emacs

and it worked. Thanks

**Comment by insanum** [comment]
Fixed: 71b053d762a332359dbb083df3438ff4c7b943dc
