### ISSUE TITLE
Farewell

### ISSUE THREAD

**Issue by samuelallan72** [insanum/sncli#135]
I'm leaving maintainership of this repository - I no longer have time, and I don't use simplenote any more.

Thanks @insanum for trusting me with your project over the years.

All the best with the future. :)

**Comment by N0ury** [comment]
Thanks for all you've done.
we're orphans now.

**Comment by insanum** [comment]
Thank you for everything @swalladge. You've been THE pioneer leading sncli for a long time. Much appreciation.

I also don't use simplenote anymore. Maybe someone will come along and would like to pick up developement.

**Comment by toozej** [comment]
In case anyone comes across this issue: I've taken over maintainership of sncli per https://github.com/insanum/sncli/pull/141#issuecomment-2920294406. More updates to come as I use sncli quite often!
