### ISSUE TITLE
disable log footer/automatic syncing

### ISSUE THREAD

**Issue by tvqt** [insanum/sncli#18]
I've been using sncli for a while, and one thing is really starting to annoy me: when I use it offline, the program is constantly trying to connect to the simplenote server, triggering the log which makes the footer pop up, and in the process, distracting me. This could be rectified with a number of different features:
- user-triggered syncing (press s to sync or something)
- an option to disable automatic syncing (or maybe sncli understanding that the internet is disconnected)
- an option to disable the log footer

**Comment by axs221** [comment]
I just checked in a change for this. For now I went with the third option. The verbose command line argument seemed to be for CLI-only mode before, but I have now extended it to apply to the urwid interface. You can tell if a note is saved if there is not an "X" in the main list, so the log footer isn't totally necessary, and I agree that it can be annoying.

Separate note, I was also running into a problem where the urllib2 library wasn't wanting to timeout when trying to connect to simplenote without a connection. urlopen timeout and socket timeout options didn't seem to help on my machine. For now I am allowing the program to not care if all notes are saved or are saving when exiting the program.

**Comment by swalladge** [comment]
Can this issue be closed now? It would seem that the original issue has been solved, and the requests library has replaced urllib2.
