### ISSUE TITLE
Ubuntu 12.04.  Error on first run.

### ISSUE THREAD

**Issue by DiagonalArg** [insanum/sncli#19]
Hi.  I'm running Ubuntu 12.04 with python 2.7 and python-urwid installed.  I ran "sudo python setup.py install" to do the install and then made a ~/.snclirc with a dummy account name.  When I run "sncli -n", I get the following error.  I don't know any python, but it looks like some problem with urwid?  Thoughts?

    sncli -n
    Traceback (most recent call last):
      File "/usr/local/bin/sncli", line 33, in <module>
        sncli.main(sys.argv[1:])
      File "/usr/local/lib/python2.7/dist-packages/simplenote_cli/sncli.py", line 1200, in main
        sncli(sync).gui(key)
      File "/usr/local/lib/python2.7/dist-packages/simplenote_cli/sncli.py", line 920, in gui
        'log'           : self.log
      File "/usr/local/lib/python2.7/dist-packages/simplenote_cli/view_titles.py", line 18, in __init__
        urwid.SimpleFocusListWalker(self.get_note_titles()))
    AttributeError: 'module' object has no attribute 'SimpleFocusListWalker'

Thanks,
/DA

**Comment by DiagonalArg** [comment]
Even with my real credentials in there, and removing the -n, I get the same error.

**Comment by axs221** [comment]
Hi DiagonalArg,

You are correct, it doesn't appear to be referencing urwid correctly. It is
a module, similar to a namespace in other languages, and it can't find
something that should be there.

Can you check the version of urwid installed? If you have pip installed,
try pip show urwid:

$ pip show urwid
---
Name: urwid
Version: 1.3.0
Location:
/usr/local/lib/python2.7/dist-packages/urwid-1.3.0-py2.7-linux-x86_64.egg
Requires:




Shawn Axsom

**Comment by DiagonalArg** [comment]
@axs211 - Well, "pip show urwid" doesn't work:

    pip show urwid
    Usage: pip COMMAND [OPTIONS]

    pip: error: No command by the name pip show
      (maybe you meant "pip install show")

But "aptitude show python-urwid" does:

    Package: python-urwid                    
    State: installed
    Automatically installed: no
    Version: 1.0.1-2
    Priority: optional
    Section: universe/python
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Architecture: amd64
    Uncompressed Size: 1,380 k
    Depends: python2.7, python (>= 2.7.1-0ubuntu2), python (< 2.8), libc6 (>= 2.2.5)
    Conflicts: python-urwid
    Provides: python2.7-urwid
    Description: curses-based UI/widget library for Python
 
    Homepage: http://excess.org/urwid/

Thanks.
/DA

**Comment by axs221** [comment]
Sorry for the delay. What if you try:

$ sudo apt-get install python-pip
$ sudo pip install urwid


It appears your version of urwid (*1.0.1-2*) is a little out-of-date. Here
is mine:

$ pip show urwid
---
Name: urwid
Version: *1.3.0*
Location:
/usr/local/lib/python2.7/dist-packages/urwid-1.3.0-py2.7-linux-x86_64.egg

Best regards,

Shawn



Shawn Axsom

**Comment by DiagonalArg** [comment]
@axs221 - that appears to do it!  (At least I've got a help command working, and logs!)  Thanks man.

Command line, here I come!

/DA.
