### ISSUE TITLE
Sync Understandings,

### ISSUE THREAD

**Issue by 7Moses** [insanum/sncli#38]
Thank you! for sncli,  

I would like to clear up my understanding of Syncing, I only see Syncing of the note I am working in with Simplenote when I use wq and not with w, nor wa, is this right,

Thanks,

**Comment by swalladge** [comment]
Correct, sncli will only save and sync a note _after_ you have saved and closed the editor. (Please correct me if you meant something else.)

**Comment by 7Moses** [comment]
Thanks for the guidance,
