### ISSUE TITLE
Issue with + sign

### ISSUE THREAD

**Issue by J-F-M** [insanum/sncli#54]
Hi there,

Loving sncli but facing an issue: it seems as least the + sign is escaped/replaced by a blank space when sending to SN. To reproduce:

- create a new note in sncli with a + sign
- synch
- check the note from another SN client or the SN web interface

Notes created from other clients or from the SN web interface keep the + sign.

This makes sncli unsuitable to store e.g. code snippets or ASCII-armored PGP blobs.

**Comment by swalladge** [comment]
:scream: Wow that's not good! I can't believe that has gone unnoticed for so long.

Thanks for reporting! :+1: 

A fix is incoming.

**Comment by J-F-M** [comment]
Excellent, thanks for the quick fix!

Now if you want a report about UTF-8 accented characters display, let me
know :)

**Comment by swalladge** [comment]
Sure, all bug reports appreciated! :+1:  I was hoping all the utf-8 issues were finally ironed out though... :cry:
