### ISSUE TITLE
Switch to pipenv

### ISSUE THREAD

**Issue by swalladge** [insanum/sncli#65]
I feel it would be useful to drop the requirements.txt and switch to using a Pipfile for a better developer experience. Thoughts?

**Comment by nbenm** [comment]
For Debian users, this is not the best.
Btw, I had to install also distutils package.

**Comment by swalladge** [comment]
Maybe it's possible to support both in the project. I'll investigate. :)

**Comment by swalladge** [comment]
Pipenv is now supported in the `next` branch.
