### ISSUE TITLE
Sync is not running in background, and log messages in gui_footer_log fill the entire screen

### ISSUE THREAD

**Issue by qcu** [insanum/sncli#7]
Sync does not run in the background. Rather, as soon as sync starts, no keyboard input is possible, and log messages "Synced new note from server (key=...)" log messages begin marching up the screen. Once the screen is filled, the log messages pause, until "Enter" is pressed, then they continue scrolling past until sncli crashes as per #6.

**Comment by insanum** [comment]
Fixed: 93a48205e39300169d7d73c62fcc39056e3a1785
