### ISSUE TITLE
Open markdown notes with markdown extension

### ISSUE THREAD

**Issue by louwers** [insanum/sncli#79]
I'd like to suggest that markdown notes are opened with a markdown extension. This way the text editor can enable markdown-specific features such as syntax highlighting.

So instead of opening e.g. `/tmp/tmpxbdsaull.txt` it would open `/tmp/tmpxbdsaull.md`.

Seems like a reasonable change to me!

**Comment by swalladge** [comment]
sncli already does this as far as I know. For any notes saved as markdown, sncli will open it with a `.mkd` extension.

**Comment by louwers** [comment]
My bad! I was opening a non-markdown note. :man_facepalming:
