### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by swalladge** [insanum/sncli#84]
Currently the only documentation available is the readme file and an in-app listing of keybinds. It would be useful to develop more extensive documentation. It would also help reduce the length of the readme.

A fork of this project made for nextcloud notes, nncli, has nice documentation which could be copied/adapted for sncli. See https://nncli.org/ and https://git.danielmoch.com/nncli/

Ideas:

- sphinx for generating the docs
- host for free on readthedocs
- shorten readme to only include important info
- include tips and tricks from wiki in actual docs
- inspiration from https://nncli.org/
- scope for more configuration examples

**Comment by 1094** [comment]
I would love to help out with this and I have a working knowledge of reStructuredText. 

I can start a document from what [nncli's configuration list](https://nncli.org/configuration.html#) has and add the readme and wiki information.

**Comment by swalladge** [comment]
Sounds awesome! Please do and create a pull request for it! :D

**Comment by 1094** [comment]
This branch isn't ready for a pull request. I was hoping you could take a look at it and let me know if this is the direction you were hoping to go.

**Comment by swalladge** [comment]
Please open a pull request and tag it [WIP]. Easier to have a discussion and comment on code there. Thanks. :)

**Comment by swalladge** [comment]
Added in #85
